### ISSUE TITLE
Related To - Objects Not Available

### ISSUE THREAD

**Issue by dravenstien** [superfell/maildrop#19]
I have 2 custom objects I have recently added to Salesforce.  This was done after I downloaded Maildrop.  Now when I try to relate an email to one of those 2 objects, they are not in the list to related them to.  Interesting thing is that some of the other new objects ARE in the list.  I tried uninstalling and reinstalling Maildrop, but no change.

**Comment by superfell** [comment]
Ensure that your custom objects have activities enabled for them. Can you related a task to them in the main salesforce web UI ?

**Comment by dravenstien** [comment]
You are right.  Activities were not enabled.  Fixed!  Thanks!
